const ITEMS = {
	GET_ITEMS: "GET_ITEMS",
	DELETE_ITEM: "DELETE_ITEM",
	ADD_ITEM: "ADD_ITEM",
	LOADING_ITEMS: "LOADING_ITEMD"
}

const USER = {
	USER_LOADING: 'USER_LOADING',
	USER_LOADED: 'USER_LOADED',
	AUTH_ERROR: 'AUTH_ERROR',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	REGISTER_FAIL: 'REGISTER_FAIL',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	GET_ERRORS: 'GET_ERRORS',
	CLEAR_ERRORS: 'CLEAR_ERRORS',
}

export { ITEMS, USER }